# don't build tags, it's redundant
if: tag IS blank

git:
  depth: 3

language: node_js

node_js:
- "node"
- "10"
- "8"

# Use faster Docker architecture on Travis.
sudo: false

cache: npm

before_install:
- if [[ "$(npm -v)" != "$(npm v npm dist-tags.latest)" ]]; then npm i -g npm@latest; fi

install:
- npm ci
- npm run install

script:
- npm run lint
- npm run test
