# don't build tags, it's redundant
if: tag IS blank

os:
  - linux

sudo: false

addons:
  chrome: stable
  firefox: latest

language: node_js

node_js:
- "node" # latest
- "12"
- "10"
- "8"

cache: npm

install:
  - npm install

stages:
  - lint
  - unit tests
  - test

jobs:
  include:
    - stage: 'lint'
      script: npm run lint
    - stage: 'unit tests'
      script: npm run test:unit

script: npm run test:it # runs implicitly in 'test' build stage
