language: node_js
dist: trusty
cache:
  directories:
    - node_modules
sudo: required
addons:
   apt:
      sources:
         - google-chrome
      packages:
         - google-chrome-stable
         # latest version of firefox already installed by default
node_js:
    - "4"
    - "6"
    - "8"
install:
   - npm install -g webdriver-manager
   - webdriver-manager update
   - npm install
before_script:
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start
   - nohup webdriver-manager start &
   - sleep 10 # give webdriver some time to start
script:
   - npm run test
   - npm run test-protractor
