# don't build tags, it's redundant
if: tag IS blank

sudo: false

git:
  depth: 3

addons:
  chrome: stable
  firefox: latest

language: node_js

os:
  - linux

node_js:
- "node"
- "lts/*"
- "8"

env:
  - NPM_TASK=ci:base
  - NPM_TASK=ci:extended

matrix:
  exclude:
    - node_js: "node"
      env: NPM_TASK=ci:extended
    - node_js: "8"
      env: NPM_TASK=ci:extended

cache: npm

install:
  - npm install

script:
  - npm run $NPM_TASK
