language: node_js
dist: trusty
node_js:
  - 'node'
  - '8'
  - '6'
  - '4'
before_install:
  - dpkg --compare-versions `npm -v` ge 3.0 || npm i -g npm@3
  - rm package-lock.json
install:
  - npm install
script:
  - node index.js
