if: tag IS blank
os:
- linux
sudo: false
addons:
  chrome: stable
  firefox: latest
language: node_js
node_js:
- node
- '12'
- '10'
- '8'
cache: npm
install:
- npm install
stages:
- lint
  #- unit tests
  #- test
jobs:
  include:
  - stage: lint
    name: 'dom-utils'
    script: cd packages/dom-utils; npm install; npm run lint
  - stage: lint
    name: 'eyes-appium'
    script: cd packages/eyes-appium; npm install; npm run lint
  - stage: lint
    name: 'eyes-common'
    script: cd packages/eyes-common; npm install; npm run lint
  - stage: lint
    name: 'eyes-images-browser'
    script: cd packages/eyes-images-browser; npm install; npm run lint
  - stage: lint
    name: 'eyes-images'
    script: cd packages/eyes-images; npm install; npm run lint
  - stage: lint
    name: 'eyes-protractor'
    script: cd packages/eyes-protractor; npm install; npm run lint
  - stage: lint
    name: 'eyes-sdk-core-browser'
    script: cd packages/eyes-sdk-core-browser; npm install; npm run lint
  - stage: lint
    name: 'eyes-sdk-core'
    script: cd packages/eyes-sdk-core; npm install; npm run lint
  - stage: lint
    name: 'eyes-selenium-jest-perf'
    script: cd packages/eyes-selenium-jest-perf; npm install; npm run lint
  - stage: lint
    name: 'eyes-selenium'
    script: cd packages/eyes-selenium; npm install; npm run lint
  - stage: lint
    name: 'eyes-testcafe'
    script: cd packages/eyes-testcafe; npm install; npm run lint
  - stage: lint
    name: 'sdk-fake-eyes-server'
    script: cd packages/sdk-fake-eyes-server; npm install; npm run lint
  - stage: lint
    name: 'sdk-test-kit'
    script: cd packages/sdk-test-kit; npm install; npm run lint
  - stage: lint
    name: 'visual-grid-client'
    script: cd packages/visual-grid-client; npm install; npm run lint
    #  - stage: unit tests
    #    node_js: node
    #    script: npm run test:unit
    #  - node_js: 12
    #    script: npm run test:unit
    #  - node_js: 10
    #    script: npm run test:unit
    #  - node_js: 8
    #    script: npm run test:unit
# The script below runs using the default 'test' build stage (a.k.a. 'Test')
# in the job dashboard. The 'test' build stage uses the node_js languages
# specified above, but the other stages & jobs need to specify the node_js
# versions explicitly...
# script: npm run test:it
notifications:
  slack:
    secure: oV4UyGK1CocNQmhUX0878NtkxgsJisAZsJVwZe7mFfsy0MhcRyQuk4Bux7acDr/hsm6zUepCUwEoJJhA7PFTSmqHQyHko4S1JDBAa70U+R4/b+KFUEzH9bEQC1PjLcA5G1uhqT35Q2ppTcjl64HWudVIDNi09+PAyYR/M2MSf29b1Uji0CLOUchpZk13OKeU1M5I/OhJiyq92wHRKb6WiimvsnorvozLJhqAvPgzCOxxy6tSoqSBuPffTUEC0+Qwc4A3lRai8MypppDl5pqM4bTsL0uwXIQEX5VDr0HK0kQwgkHGAFzUjg4JOrCxVxQY9kGwiymJU8JbkkPMc0QIWjV73wVITzSGz2qHMCmpyAky+mLNxYrZ8SbadrO6g7r2bgp0uQOfzB7TktDIT0/gQriw+tovkda5xoyp6YQFHHtIu/KjD2PnCymXJH43kjwcXcRHapG8RJpJjlNinEQ+FxHgU059Kebjk9/Qpnx016Q54PgO/mP1JG8OnslZkvIVPfB20K+VMnAGr3z7xek0bqJcD2439MzQulyL/60nqPqM6JBdL6oh6BxuBpAY7v9Bk+KkLHpwu6DOzmgRn6r0cc75ep2lAKS5HPW2FVFwve9poeQpwkuNna1qoqDM5ezWo7S8WJ1KMT/kaTwprqxcRAKk3iFhaTSny6m4O4qpQqk=
