# don't build tags, it's redundant
if: tag IS blank

sudo: false

git:
  depth: 3

addons:
  chrome: stable
  firefox: latest

language: node_js

os:
  - linux

node_js:
- "node" # latest
- "12"
- "10"
- "8"

cache: false

install:
  - npm install

script:
  - npm run lint
  - npm run test:unit
  - npm run test:it
