if: tag IS blank
sudo: false
git:
  depth: 3
addons:
  chrome: stable
  firefox: latest
language: node_js
os:
- linux
node_js:
- node
- lts/*
- '6'
cache: npm
env:
  matrix:
  - SELENIUM_VERSION=2 PROTRACTOR_VERSION=4
  - SELENIUM_VERSION=3 PROTRACTOR_VERSION=5
stages:
- lint
- test
- Integration tests
- name: End-to-end tests
  if: branch = master
install:
- npm install selenium-webdriver@^$SELENIUM_VERSION protractor@^$PROTRACTOR_VERSION
- npm install
- npm install webdriver-manager
- webdriver-manager update
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- webdriver-manager start &
- sleep 10
script:
- npm run test:unit
jobs:
  include:
  - stage: lint
    node_js: lts/*
    script: npm run lint
  - stage: Integration tests
    node_js: '6'
    script: npm run test:it
  - stage: End-to-end tests
    node_js: '6'
    script: npm run test:e2e
after_script:
- sh -e /etc/init.d/xvfb stop
notifications:
  slack:
    secure: FEPb3buWp03BRy2Uo+yojWO1Xqq7lZx2lDgacpMBzk+IJl777TwlefOvAk2S0hLVwJtunG0hXvzimlkyOOO2azLl6ADOnMh9XXa3XsOXle0Yd05JqHJ6ZGa4oU/TRjODyuV/0gQ2RUfMn9dDhcEcCufAFqIQyjrDu+reRKGAC7s=
