sudo: required
language: node_js
node_js:
  - "node"
services:
  - docker
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"  
  - docker pull selenium/standalone-chrome
  - docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:3.11.0-antimony
  - yarn global add selenium-side-runner
script:
  - selenium-side-runner tests/*.side --server http://localhost:4444/wd/hub
  - yarn lint
  - yarn test
  - yarn release
