# don't build tags, it's redundant
if: tag IS blank

sudo: false

git:
  depth: 3

addons:
  chrome: stable
  firefox: latest

language: node_js

os:
  - linux

node_js:
- "node"
- "lts/*"
- "8"

cache: npm

install:
  - npm install

stages:
  - lint
  - test
  - it test
  - name: e2e test
    if: branch = master

jobs:
  include:
    - stage: lint
      node_js: "lts/*"
      script: npm run lint
    - stage: test
      name: "Unit Tests"
      script: npm run test:unit
    - stage: it test
      node_js: "8"
      name: "Integration  Tests"
      script: npm run test:it
    - stage: e2e test
      node_js: "8"
      name: "End-To-End  Tests"
    - script: npm run test:e2e
