# don't build tags, it's redundant
if: tag IS blank

sudo: false

git:
  depth: 3

addons:
  chrome: stable
  firefox: latest

language: node_js

os:
  - linux

node_js:
- "lts/*"
- "10"
- "8"

cache: false

install:
  - npm install

stages:
  - lint
  - test

script:
  - npm ls
  - npm run test:unit

jobs:
  include:
    - stage: lint
      node_js: "lts/*"
      script: npm run lint
    - stage: test
      script: npm run test:it
