if: tag IS blank
os:
- linux
sudo: false
addons:
  chrome: stable
  firefox: latest
language: node_js
node_js:
- lts/*
cache:
  yarn: true
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn -v
install:
- yarn install
jobs:
  include:
  - stage: lint
    script: yarn lint
  - name: "@applitools/dom-utils"
    script: cd packages/dom-utils; yarn test
    stage: test
  - name: "@applitools/eyes-common"
    script: cd packages/eyes-common; yarn test
  - name: "@applitools/eyes-images"
    script: cd packages/eyes-images; yarn test
  - name: "@applitools/eyes-sdk-core"
    script: cd packages/eyes-sdk-core; yarn test
  - name: "@applitools/eyes-selenium"
    script: cd packages/eyes-selenium; yarn test
  - name: "@applitools/eyes-testcafe"
    script: cd packages/eyes-testcafe; yarn test
  - name: "@applitools/sdk-fake-eyes-server"
    script: cd packages/sdk-fake-eyes-server; yarn test
  - name: "@applitools/sdk-test-kit"
    script: cd packages/sdk-test-kit; yarn test
  - name: "@applitools/visual-grid-client"
    script: cd packages/visual-grid-client; yarn test
  - name: "@applitools/eyes.webdriverio"
    script: cd packages/eyes-webdriverio-4; yarn test
  - name: "@applitools/eyes-webdriverio"
    script: cd packages/eyes-webdriverio-5; yarn test
  - name: "@applitools/eyes-webdriverio5-service"
    script: cd packages/eyes-webdriverio-5-service; yarn test
notifications:
  slack:
    secure: oV4UyGK1CocNQmhUX0878NtkxgsJisAZsJVwZe7mFfsy0MhcRyQuk4Bux7acDr/hsm6zUepCUwEoJJhA7PFTSmqHQyHko4S1JDBAa70U+R4/b+KFUEzH9bEQC1PjLcA5G1uhqT35Q2ppTcjl64HWudVIDNi09+PAyYR/M2MSf29b1Uji0CLOUchpZk13OKeU1M5I/OhJiyq92wHRKb6WiimvsnorvozLJhqAvPgzCOxxy6tSoqSBuPffTUEC0+Qwc4A3lRai8MypppDl5pqM4bTsL0uwXIQEX5VDr0HK0kQwgkHGAFzUjg4JOrCxVxQY9kGwiymJU8JbkkPMc0QIWjV73wVITzSGz2qHMCmpyAky+mLNxYrZ8SbadrO6g7r2bgp0uQOfzB7TktDIT0/gQriw+tovkda5xoyp6YQFHHtIu/KjD2PnCymXJH43kjwcXcRHapG8RJpJjlNinEQ+FxHgU059Kebjk9/Qpnx016Q54PgO/mP1JG8OnslZkvIVPfB20K+VMnAGr3z7xek0bqJcD2439MzQulyL/60nqPqM6JBdL6oh6BxuBpAY7v9Bk+KkLHpwu6DOzmgRn6r0cc75ep2lAKS5HPW2FVFwve9poeQpwkuNna1qoqDM5ezWo7S8WJ1KMT/kaTwprqxcRAKk3iFhaTSny6m4O4qpQqk=
env:
  jobs:
    - APPLITOOLS_SERVER_URL=https://testonpremeyes.applitools.com
  global:
    secure: DJ34msWWAzU6GBlOi10QWuYpWikRqyifSsNDUQOhZG263OpiEYvtBusrYHkM3kFFcHtKOBcTD35IljHnWCbqwHP7rHIvDs36hFyn8dckIJBnNyqyHl3h/PlDi3jDSrTBSK72NkX3/tofetkD1wuadzPzIQ6COpFZnivFDMGB3PXRIRjuM05sU6Z0NGeI+wtkux+ujslI59q5Qn7XVugNhyGC9hZeTKe66cDf5HqgMLFfAZDjpiffSHKuFWF+Rb0Xn46XuJBX0dPU0epT5D9aU5YeZBULYEMPj3nnXV+BeQjVRlLIHcivfWPIKOcPEK6tpj/gfNmI+1aMddGVDneq5F7Aze2hUV+Q8LyCxNYtHO1dkrgb1Zaj2gkBMbKak6tKJYJxx3flXiuFXcawpCB4P95Alh2SkC2tlizi9wbC1KxLtEiBKIYq5R2bB4xFOtjWCQcHsfEHvCJLfExpawuS+J8F/CejLI8iaDL7DAwTY4wzan5r9W7cZ3P0rFG2Wk8e7hUlSdifVZb1fbCwOWb86LVPH7FEG6hNrKxQkOZLabShkc+mY85wNFjM+0rXD3knLCx5A4OmNZaB07o89uTR01CFLS0QdHEcl7O7tOImuXPSmWEnFJqRtw3YN8vcCptbT5GuC5/d4W4UjZ3nh01c3BaROn0hsCn2qFR/t0ZiD0s=
