version: '3'
services:
  chrome:
    image: "selenium/standalone-chrome:3.141.59-20200515"
    volumes:
      - "/dev/shm:/dev/shm"
    ports:
      - "4444:4444"
  firefox:
    image: "selenium/standalone-firefox"
    volumes:
      - "/dev/shm:/dev/shm"
    ports:
      - "4445:4444"